Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu-14.04"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network "private_network", ip: "127.0.0.100"

  config.vm.hostname = "ci-server"

  config.vm.provider :virtualbox do |vb|
    vb.name = "ci-server"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.synced_folder ".", "/vagrant_data"

end
